services:
  postgres:
    image: postgres:17.6
    container_name: task-mgmt-postgres
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    # networks:
    #   - task-mgmt-network

volumes:
  postgres_data:
# networks:
#   task-mgmt-network:
#     driver: bridge
