services:
  rabbitmq:
    image: rabbitmq:4.1.3-management-alpine
    container_name: task-mgmt-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - task-mgmt-network

volumes:
  rabbitmq_data:

networks:
  task-mgmt-network:
    external: true
